# Numpy Array

##### What is NumPy?

- NumPy is a Python library used for working with arrays, images, matrix etc

- It also has functions for working in domain of linear algebra, fourier transform, and matrices.

- NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

- NumPy stands for Numerical Python.


### Why Use NumPy?

- In Python we have lists that serve the purpose of arrays, but they are slow to process.
- NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

- NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

- This behavior is called locality of reference in computer science.

#### Install 

- we need to install the numpy before we use it, as it is not a builtin module.

pip install numpy

In [ ]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [ ]:
a=10
b=20
a
b

In [ ]:
#importing

import numpy

#alias
import numpy as np

In [ ]:
dir(np)

In [6]:
lst = ["vbhvh", 2.0, 3]

print(lst , type(lst))

print(type(lst[0]),type(lst[1]))

['vbhvh', 2.0, 3] <class 'list'>
<class 'str'> <class 'float'>


In [18]:
import numpy as np

arr = np.array([2, 2, 3.5])
print(arr)
print(type(arr))

[2.  2.  3.5]
<class 'numpy.ndarray'>


In [19]:
arr[0]
arr[2]
# arr[3]=10 
print(type(arr[2]))

2.0

3.5

<class 'numpy.float64'>


In [20]:
#Upcasting:

In [21]:
arr = np.array([1, 2, 3.0,40.2,39.4 ,True])
print(arr[0],type(arr[0]))
print(arr)

1.0 <class 'numpy.float64'>
[ 1.   2.   3.  40.2 39.4  1. ]


In [22]:
print(arr[1])
print(type(arr[1]))

2.0
<class 'numpy.float64'>


In [23]:
# numpy.array([])

In [24]:
#two dimensions

In [28]:
# python list 2D

lst2D = [[1, 2], [3, 4]]

print(lst2D[0][1])

2


In [26]:
 a2d= np.array([[1, 2], [3, 4]])

In [29]:
a2d[0,1] #[row,col]
a2d[1][1]
a2d[-1][-1]
a2d[-1][-1]

2

4

4

4

In [30]:
print(a2d.shape)

(2, 2)


In [31]:
#Minimum dimensions 2:

In [32]:
a = np.array([1, 2, 3], ndmin=5)

In [33]:
a.shape

(1, 1, 1, 1, 3)

In [34]:
print(a)

[[[[[1 2 3]]]]]


In [35]:
#3
a[0][0][0][0][2]

3

In [38]:

arr=np.array([1, 2, 3,5,10,2,291,2782,10991], ndmin=4)
arr

array([[[[    1,     2,     3,     5,    10,     2,   291,  2782,
          10991]]]])

In [39]:
#checking the dimension
arr.shape

len(arr)

print(arr)

# print(arr[0][0][0,7])
print(arr[0])
print(arr[0][0])
print(arr[0][0][0])
print(arr[0][0][0][4])
print(arr[0,0,0,4])

(1, 1, 1, 9)

1

[[[[    1     2     3     5    10     2   291  2782 10991]]]]
[[[    1     2     3     5    10     2   291  2782 10991]]]
[[    1     2     3     5    10     2   291  2782 10991]]
[    1     2     3     5    10     2   291  2782 10991]
10
10


In [ ]:
#dtype

In [40]:
 np.array([1+2j, 2, 3], dtype=complex) #x+yj

array([1.+2.j, 2.+0.j, 3.+0.j])

In [41]:
 np.array([1, 2, 3], dtype=str)

array(['1', '2', '3'], dtype='<U1')

In [47]:
bool(0)
bool(0.0)
bool([])
bool(())
bool(set())
bool({})
bool("")

False

False

False

False

False

False

False

In [45]:
 np.array([1, 2, 0,{}], dtype=bool)

array([ True,  True, False, False])

In [ ]:
#Data-type consisting of more than one element:

In [48]:
x = np.array([(1,2),(3,4)],dtype=[('f','f'),('b','<i4')])
x

array([(1., 2), (3., 4)], dtype=[('f', '<f4'), ('b', '<i4')])

In [50]:
a=np.array([1, 2, 3], dtype='f')
a
type(a[0])

array([1., 2., 3.], dtype=float32)

numpy.float32

In [51]:
print(x[0][1])
type(x[0][0])
type(x[0][1])
type(x[1][0])
type(x[1][1])

2


numpy.float32

numpy.int32

numpy.float32

numpy.int32

In [ ]:
numpy.array([] ,ndim=0,dtype=None)


##### Creating an array from sub-classes:

In [52]:
a = np.mat(np.array([[1, 2],[4,7]]))
a.shape

(2, 2)

In [53]:
arr=np.mat(np.array([[1, 2,3],[98,7,67]]))
arr.shape
print(arr[0,2]) #3rd element on the 1 dimensin

print(arr[1,0])

(2, 3)

3
98


In [54]:
np.mat('1 2; 3 5;3 4')

matrix([[1, 2],
        [3, 5],
        [3, 4]])

# numpy.asarray
- Convert the input to an array.
- Convert a list into an array:

In [55]:
 a = [1, 2]
type(a)

list

In [56]:
b = np.asarray(a)
b
type(b)

array([1, 2])

numpy.ndarray

In [57]:
a = np.array([1, 2]) #Existing arrays are not copied
type(a)

numpy.ndarray

In [58]:
np.asarray((1,2))

array([1, 2])

In [ ]:
#If dtype is set, array is copied only if dtype does not match:

In [59]:
# np.int8
# np.int16 ,32,64
# np.float32,64


In [60]:
a = np.array([1, 2], dtype=np.float64)
a
type(a[0])

array([1., 2.])

numpy.float64

In [61]:
a
type(a)

array([1., 2.])

numpy.ndarray

In [62]:
b = np.asarray([1,2])
b
type(b) 
id(b)
id(a)
a is b

array([1, 2])

numpy.ndarray

1833590362928

1833589719952

False

In [63]:
np.asarray([1,2])

array([1, 2])

In [64]:
id(np.asanyarray([1,2], dtype=np.float32))

1833590467344

In [ ]:
id(a)

In [65]:
a=10
b=10
id(a),id(b)
a is b

(140737403168848, 140737403168848)

True

In [ ]:
# ndarray subclasses are not passed through

In [67]:
class B:
    pass
class A:
    a=10
obj=A()

isinstance(obj,B)

False

In [70]:
class myAge:
  age = 36

class myObj(myAge):
  name = "John"
  age = myAge

x = issubclass(myObj,myAge)
print(x)

True


In [71]:
issubclass(np.matrix, np.ndarray)

True

In [ ]:
### np.asanyarray(obj)

In [72]:
a = np.matrix([[1, 2]])

print(a)

a=[1,23,3]
# a={1,2,3,4}
# a=(1,2,3,4)

np.asanyarray(a)


[[1 2]]


array([ 1, 23,  3])

In [73]:
np.asarray(a)  is a

False

In [74]:
a = np.asanyarray([1,2,3])
b = a
a is b 

True

#### numpy.copy

In [75]:
np.array(a, copy=True)

array([1, 2, 3])

In [76]:
#Create an array x, with a reference y and a copy z:

In [78]:
x = np.array([1, 2, 3])
x , type(x)

(array([1, 2, 3]), numpy.ndarray)

In [79]:
y = x #alias
y

array([1, 2, 3])

In [80]:
z = np.copy(x)
z

array([1, 2, 3])

In [81]:
x
y
z

array([1, 2, 3])

array([1, 2, 3])

array([1, 2, 3])

In [82]:
id(x) , id(y)
id(y) , id(z)
id(z) , id(x)

(1833590523632, 1833590523632)

(1833590523632, 1833590522960)

(1833590522960, 1833590523632)

In [83]:
y[0] = 100
y

array([100,   2,   3])

In [84]:
x

array([100,   2,   3])

In [85]:
z

array([1, 2, 3])

In [86]:
z[0] = 200

In [87]:
id(x)

1833590523632

In [88]:
id(y)

1833590523632

In [89]:
x

array([100,   2,   3])

In [90]:
y

array([100,   2,   3])

In [91]:
id(x) 

1833590523632

In [92]:
id(z)

1833590522960

In [ ]:
names = ["IND","US","AUZ"]

a = names #alias

b = names.copy()#copy will separate memory location.

print(id(names), id(a))

print(id(a), id(b))


b[1] = "USA"

print(names,a ,b)


a[2]="ENG"

print(names,a,b)

# numpy.fromfunction

In [93]:
#Construct an array by executing a function over each coordinate.

In [94]:
import numpy as np

np.fromfunction(lambda i, j: i == j, (3, 3), dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [96]:
np.fromfunction(lambda i, j: i + j, (10, 3), dtype=int)

array([[ 0,  1,  2],
       [ 1,  2,  3],
       [ 2,  3,  4],
       [ 3,  4,  5],
       [ 4,  5,  6],
       [ 5,  6,  7],
       [ 6,  7,  8],
       [ 7,  8,  9],
       [ 8,  9, 10],
       [ 9, 10, 11]])

In [ ]:
#Create a new 1-dimensional array from an iterable object.

In [97]:
[x*x for x in range(5)]

[0, 1, 4, 9, 16]

In [98]:
iterable = (x*x for x in range(5))
iterable

<generator object <genexpr> at 0x000001AAEA850430>

In [99]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [ ]:
#A new 1-D array initialized from text data in a string

In [100]:
a = np.fromstring('234->234',sep='->')
a
a.shape

array([234., 234.])

(2,)

In [101]:
np.fromstring('1, 2', dtype=int, sep=',')


array([1, 2])

In [102]:
a=10
b=20
print(f"sum of two numbers {a}+{b}={a+b}")

sum of two numbers 10+20=30


# data types

In [ ]:
np.array()
np.asarray()
np.mat()
np.matrix()
np.asanyarray()

In [103]:
my_list = [1,2,3]
print("Type of my list",type(my_list))

import numpy as np

arr = np.array(my_list)

print("Type/Class of this object:",type(arr))
print("Here is the vector\n--------------------\n",arr)

Type of my list <class 'list'>
Type/Class of this object: <class 'numpy.ndarray'>
Here is the vector
--------------------
 [1 2 3]


In [104]:
my_mat = [[1.1,2,3],[4,5,6],[7,8,9]]
mat = np.asarray(my_mat)
print("Type/Class of this object:",type(mat))
print("Here is the matrix\n----------\n",mat,"\n----------")
print("Dimension of this matrix: ",mat.ndim,sep='') #ndim gives the dimensison, 2 for a matrix, 1 for a vector
print("Size of this matrix: ", mat.size,sep='') #size gives the total number of elements
print("Shape of this matrix: ", mat.shape,sep='') #shape gives the number of elements along each axes (dimension)
print("Data type of this matrix: ", mat.dtype,sep='') #dtype gives the data type contained in the array


Type/Class of this object: <class 'numpy.ndarray'>
Here is the matrix
----------
 [[1.1 2.  3. ]
 [4.  5.  6. ]
 [7.  8.  9. ]] 
----------
Dimension of this matrix: 2
Size of this matrix: 9
Shape of this matrix: (3, 3)
Data type of this matrix: float64


In [110]:
my_mat = [[1.1,2,3],[4,5,6],[7,8,9]]
mat = np.asarray(my_mat)
print(mat.shape)

print(mat.dtype)

print(mat.size)

print(mat.ndim)

(3, 3)
float64
9
2


In [111]:
my_mat = [[1.1,2,3],[4,5.2,6],[7,8.3,9]]
mat = np.array(my_mat)
print("Data type of the modified matrix: ", mat.dtype,sep='') #dtype gives the data type contained in the array
print("\n\nEven tuples can be converted to ndarrays...")


Data type of the modified matrix: float64


Even tuples can be converted to ndarrays...


In [112]:
b = np.array([(1.5,2,3), (4,5,6)])
print("We write b = np.array([(1.5,2,3), (4,5,6)])")
print("Matrix made from tuples, not lists\n---------------------------------------")
print(b)

We write b = np.array([(1.5,2,3), (4,5,6)])
Matrix made from tuples, not lists
---------------------------------------
[[1.5 2.  3. ]
 [4.  5.  6. ]]


# arange and linspace

In [116]:
list(range(2,10,2)) #integers 

[2, 4, 6, 8]

In [117]:
list(range(1.5,10.5))

TypeError: 'float' object cannot be interpreted as an integer

In [119]:
np.arange(0,16,2)
np.arange(5,16,2.3) # A series of numbers from low to high , it also takes the float values

array([ 0,  2,  4,  6,  8, 10, 12, 14])

array([ 5. ,  7.3,  9.6, 11.9, 14.2])

In [120]:
np.arange(5.5,16.5,2.2)

array([ 5.5,  7.7,  9.9, 12.1, 14.3])

In [121]:
list(range(5,16,2))

[5, 7, 9, 11, 13, 15]

In [123]:
list(range(50,-1,-5))

[50, 45, 40, 35, 30, 25, 20, 15, 10, 5, 0]

In [124]:
np.arange(50,-1,-5.2)# Numbers spaced apart by 2

array([50. , 44.8, 39.6, 34.4, 29.2, 24. , 18.8, 13.6,  8.4,  3.2])

In [125]:
np.arange(0,11,2.5) # Numbers spaced apart by 2.5

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [126]:
np.arange(5.0,-1,-5)

array([5., 0.])

In [128]:
list(range(1,2))

[1]

In [134]:
#printing the numbers in the given range 
(np.linspace(1,10,1000))#start, stop , nums

array([ 1.        ,  1.00900901,  1.01801802,  1.02702703,  1.03603604,
        1.04504505,  1.05405405,  1.06306306,  1.07207207,  1.08108108,
        1.09009009,  1.0990991 ,  1.10810811,  1.11711712,  1.12612613,
        1.13513514,  1.14414414,  1.15315315,  1.16216216,  1.17117117,
        1.18018018,  1.18918919,  1.1981982 ,  1.20720721,  1.21621622,
        1.22522523,  1.23423423,  1.24324324,  1.25225225,  1.26126126,
        1.27027027,  1.27927928,  1.28828829,  1.2972973 ,  1.30630631,
        1.31531532,  1.32432432,  1.33333333,  1.34234234,  1.35135135,
        1.36036036,  1.36936937,  1.37837838,  1.38738739,  1.3963964 ,
        1.40540541,  1.41441441,  1.42342342,  1.43243243,  1.44144144,
        1.45045045,  1.45945946,  1.46846847,  1.47747748,  1.48648649,
        1.4954955 ,  1.5045045 ,  1.51351351,  1.52252252,  1.53153153,
        1.54054054,  1.54954955,  1.55855856,  1.56756757,  1.57657658,
        1.58558559,  1.59459459,  1.6036036 ,  1.61261261,  1.62

# Matrix creation

In [135]:
print("Vector of zeroes\n---------------------")
print(np.zeros(10))

Vector of zeroes
---------------------
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
print("Matrix of zeroes\n--------------------")
print(np.zeros((6,7))) # Notice Tuples

In [ ]:
print("Vector of ones\n---------------------")
print(np.ones(5))

In [ ]:
print("Matrix of ones\n---------------------")
a=np.ones([5,2,8])
a# Note matrix dimension specified by Tuples
a.shape
a.size
a[0][0][0]

In [ ]:
print("Matrix of 5's\n---------------------")
print(5+np.ones((3,5)))

In [ ]:
print("Empty matrix\n-------------\n", np.empty((2,3)))

In [ ]:
mat1 = np.eye(4) 
print("Identity matrix of dimension", mat1.shape)
print(mat1)

In [ ]:
np.arange(3)

In [ ]:
np.arange(3.0)

In [ ]:
 np.arange(3,7)

In [ ]:
np.arange(3,7,2)

In [ ]:
np.linspace(2.0, 3.0, num=100)

In [ ]:
np.linspace(2.0, 3.0, num=5, endpoint=True)

In [ ]:
np.linspace(2.0, 3.0, num=9, retstep=True)

In [ ]:
import numpy as np
np.logspace(2.0, 3.0, num=10,base = 10)

In [ ]:
np.logspace(2.0, 3.0, num=4, endpoint=False)

In [ ]:
np.logspace(2.0, 3.0, num=20, base=2.0)

In [ ]:
#Extract a diagonal or construct a diagonal array.

In [ ]:
x = np.arange(16)
x

In [ ]:
x.shape
x

In [ ]:
x.reshape(4,4)

In [ ]:
x = np.array([[1,2,3,4],[5,6,7,78],[11,22,33,44],[23,32,12,45]])
x
np.diag(x) #print only dialgnol elements

In [ ]:
np.diag(x, k=-3)

In [ ]:
np.diag(x, k=-1)

In [ ]:
np.diag(np.diag(x))

# Random number generation

In [ ]:
import random as rd

dir(rd)

In [ ]:
for i in range(1,10): print(rd.randint(1,10)) #int

In [ ]:
rd.random() #float

In [ ]:
for i in range(10): print(rd.randrange(1,10,2))

In [ ]:
from numpy.random import *

In [ ]:


rand(2,2)

In [ ]:
print("Random number generation (from Uniform distribution)")
print(np.random.rand(2,3)) # 2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary 

In [ ]:
np.random.rand(1000)

In [ ]:
import pandas as pd

df = pd.DataFrame(np.random.rand(1000)) #uniform distribution
# df.plot()

In [ ]:
df

In [ ]:
type(df)

In [ ]:
df.plot()

In [ ]:
print("Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
print(np.random.randn(4))

In [ ]:
import pandas as pd

df = pd.DataFrame(np.random.randn(10000))
df.plot()

In [ ]:
print("Random integer vector:",np.random.randint(1,10)) #randint (low, high, # of samples to be drawn)
print ("\nRandom integer matrix")


In [ ]:
print(np.random.randint(1,100,(4,4))) #randint (low, high, # of samples to be drawn in a tuple to form a matrix)
print("\n20 samples drawn from a dice throw:",np.random.randint(1,7,20)) # 20 samples drawn from a dice throw

# Reshaping

In [ ]:
from numpy.random import randint as ri
a = ri(1,50,30)
# print(a)

# print(a.shape)

# b = a.reshape(2,3,5)
# print(b)
# print(b.shape)

c = a.reshape(6,-1)
c
print(c)
a.reshape(15,2)

In [ ]:
print ("Shape of a:", a.shape)
print ("Shape of b:", b.shape)
print ("Shape of c:", c.shape)


In [ ]:
print("\na looks like\n",'-'*20,"\n",a,"\n",'-'*20)
print("\nb looks like\n",'-'*20,"\n",b,"\n",'-'*20)
print("\nc looks like\n",'-'*20,"\n",c,"\n",'-'*20)


In [ ]:
from numpy.random import randint as ri

In [ ]:
ri(1,10,(2,2))
np.random.seed(123)

In [ ]:
A = ri(1,100,10)# Vector of random interegrs
np.random.seed(123)
print(A)
print("\nVector of random integers\n",'-'*50,"\n",A)
print("\nHere is the sorted vector\n",'-'*50,"\n",-np.sort(-A))


In [ ]:
M = ri(1,100,25).reshape(5,5) # Matrix of random interegrs
#print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",np.sort(M, kind='mergesort')) # Default axis =1
print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M, axis=1, kind='mergesort'))
M

In [ ]:
b

In [ ]:
print("Max of a:", M.max())
print("Max of b:", b.max())
b

In [ ]:
M

In [ ]:
print("Max of a location:", M.argmax(axis= 0))#axiz = 0 > row
print("Max of b location:", b.argmax())
print("Max of c location:", b.argmax())

# Indexing and slicing

In [ ]:
some_list = ["ajka",True,10,203]
some_list[-1]

In [ ]:
import numpy as np
arr = np.arange(0,11)
print("Array:",arr)


In [ ]:
print("Element at 7th index is:", arr[7])


In [ ]:
print("Elements from 3rd to 5th index are:", arr[3:6])


In [ ]:
print("Elements up to 4th index are:", arr[:4])
arr

In [ ]:
a = [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]
a[-1:7:-1]

In [ ]:
print("Elements from last backwards are:", arr[-1:7:-1]) #-1 0 1 2 3 4 5 6 7


In [ ]:
print("3 Elements from last backwards are:", arr[-1:-6:2])


In [ ]:
arr = np.arange(0,21,2)
print("New array:",arr)


In [ ]:
print("Elements at 2nd, 4th, and 9th index are:", arr[[2,4,9]]) # Pass a list as a index to subset

In [ ]:
import numpy as np 
mat = np.array(np.linspace(10,100,30,dtype=int)).reshape(6,5)
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)


In [ ]:
mat[1:4]
# [rows,columns]

In [ ]:
mat[2:5,1:4]

In [ ]:
mat[:,[1,3,2]]

In [ ]:
mat[0:3,[1,3]]
mat

In [ ]:
print("\nDouble bracket indexing\n------------------------")
print("Element in row index 1 and column index 2:", mat[4][3])
mat

In [ ]:
print("\nSingle bracket with comma indexing\n----------------------------------")
print("Element in row index 1 and column index 2:", mat[4,3])
print("\nRow or column extract\n----------------------")


In [ ]:
print("Entire row at index 2:", mat[2])
print("Entire column at index 3:", mat[:,3])


In [ ]:
print("\nSubsetting sub-matrices\n--------------------------")
print("Matrix with row indices 1 and 2 and column indices 3 and 4\n", mat[1:3,3:5])


In [ ]:
print("Matrix with row indices 0 and 1 and column indices 1 and 3\n", mat[0:2,[1,3]])

# Array Math

In [ ]:
import numpy as np

from numpy.random import randint as ri

In [ ]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n------------\n",mat2)


In [ ]:
print("\nSq-root of 1st matrix using np\n------------------\n", np.sqrt(mat1))


In [ ]:
print("\nExponential power of 1st matrix using np\n",'-'*50,"\n", np.exp(mat1))


In [ ]:
print("\n10-base logarithm on 1st matrix using np\n",'-'*50,"\n", np.log10(mat1))
print(mat1)
print(mat2)

In [ ]:
print("\nModulo reminder using np\n",'-'*50,"\n", np.fmod(mat1,mat2))
mat1%mat2

In [ ]:
print("\nCombination of functions by shwoing exponetial decay of a sine wave\n",'-'*70)

In [ ]:
A = np.linspace(0,12*np.pi,1001)


In [ ]:
A

In [ ]:
np.pi


In [ ]:
#as np
np.array
np.asarray
np.asanyarray

#random
np.random.rand()
np.random.randn
np.random.randint
np.random.random
# FUnction
np.fromfunction
np.fromstring
np.fromiter

#general
np.sort()
np.sqrt()
np.expo(),log10(),sum()
np.reshape()
#attributes
shape
dtypes
ndim
index


In [ ]:
#IMAGE to NUMPY ARRAY 

from PIL import Image

img = Image.open("nature.jpg")

print(img)

print(img.format)

print(img.size)

print(img.mode)

In [ ]:

from PIL import Image
import numpy as np

img = Image.open("nature.jpg")

Numpyimg = np.asarray(img)

print(Numpyimg.shape)

In [ ]:
revertedImage = Image.fromarray(Numpyimg)
print(revertedImage)

In [ ]:
print(revertedImage.show())